language: java
jdk: openjdk10
install: true
before_install:
  - export M2_HOME=$HOME/apache-maven-3.5.4
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH
script: ./mvnw initialize && ./mvnw clean install && ./mvnw verify -DskipITs=false
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.4"